<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Analytics - Assignment 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="A1_Quarto_files/libs/clipboard/clipboard.min.js"></script>
<script src="A1_Quarto_files/libs/quarto-html/quarto.js"></script>
<script src="A1_Quarto_files/libs/quarto-html/popper.min.js"></script>
<script src="A1_Quarto_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="A1_Quarto_files/libs/quarto-html/anchor.min.js"></script>
<link href="A1_Quarto_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="A1_Quarto_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="A1_Quarto_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="A1_Quarto_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="A1_Quarto_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analytics - Assignment 1</h1>
<p class="subtitle lead"><strong>Cape Town Airbnb Listing Analysis</strong></p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ben Mitchell &amp; Ben Frost </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction:</h2>
<p>The following report presents a supervised learning analysis of Airbnb listing data for the city of Cape Town. Based on any given listing observation the analysis aims to predict whether or not a host leases more than a threshold number of properties on Airbnb in which case they are termed a ‘High Host’ and explore this response’s potential housing-market impact. Using a curated 2025 dataset of listings, this analysis develops and compares several classification models in order to identify patterns in listing characteristics that are associated with whether or not its host is considered a ‘High Host’.</p>
<p>The analysis follows a structured predictive modelling workflow. The data are first divided into training and test sets so that model development and out of sample performance evaluation remain separate. The decision rule for what constitutes a ‘High Host’ is then derived and defined with the property number threshold being determined using the training data. Several classification models are subsequently fitted and tuned, the models types include elastic-net logistic regression, random forest, boosted trees and k-nearest neighbours. Their performance is compared using 10-fold cross-validation and a common set of evaluation metrics.</p>
<p>Beyond model comparison, this report also considers decision-threshold optimisation, since the best threshold number of properties for classification may differ from the default value when the objective is to improve the F1 score. The best performing model is selected and then interpreted using variable-importance and effect plots. Additionally, its prediction errors are examined through false-positive and false-negative cases. This report aims not only to assess predictive performance but also to demonstrate interpretable modelling processes.</p>
</section>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1:</h2>
<section id="target-variable-creation" class="level3">
<h3 class="anchored" data-anchor-id="target-variable-creation">Target Variable Creation:</h3>
<p>This project will be modelling the binary target variable fitted to the Host Listings Count, the number of listings the host has (per Airbnb unknown calculations), above some variable to be defined, x.</p>
<p>There have been concerns in Cape Town regarding the massive influx of Airbnb short term rentals, which have had effects on the affordability and availability of long term-rentals. This binary target variable aims to discover what factors can describe listings that are attractive to professional Airbnb hosts who have portfolios of listings.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>hostUniqueTrain <span class="ot">&lt;-</span> trainDataC <span class="sc">|&gt;</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(host_id, host_listings_count)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>HHtrain <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">mean</span>(hostUniqueTrain<span class="sc">$</span>host_listings_count <span class="sc">&gt;</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>nHHtrain <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">-</span> HHtrain, <span class="dv">2</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>hostUniqueTest <span class="ot">&lt;-</span> testDataC <span class="sc">|&gt;</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(host_id, host_listings_count)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>HHtest <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">mean</span>(hostUniqueTest<span class="sc">$</span>host_listings_count <span class="sc">&gt;</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>nHHtest <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">-</span> HHtest, <span class="dv">2</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>imbalanceTable <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">Dataset =</span> <span class="fu">c</span>(<span class="st">"Training"</span>, <span class="st">"Test"</span>),</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">HighHost =</span> <span class="fu">c</span>(HHtrain, HHtest),</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">Not_HighHost =</span> <span class="fu">c</span>(nHHtrain, nHHtest)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>latexTable <span class="ot">&lt;-</span> <span class="fu">kable</span>(</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  imbalanceTable,</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Class imbalance for x = 2 on the training and test data"</span>,</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Dataset"</span>, <span class="st">"HighHost (%)"</span>, <span class="st">"Not HighHost (%)"</span>),</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">format =</span> <span class="st">"latex"</span>,</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">align =</span> <span class="fu">c</span>(<span class="st">"l"</span>, <span class="st">"c"</span>, <span class="st">"c"</span>)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(latexTable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>\begin{table}

\caption{\label{tab:unnamed-chunk-4}Class imbalance for x = 2 on the training and test data}
\centering
\begin{tabular}[t]{lcc}
\toprule
Dataset &amp; HighHost (\%) &amp; Not HighHost (\%)\\
\midrule
Training &amp; 27.41 &amp; 72.59\\
Test &amp; 40.42 &amp; 59.58\\
\bottomrule
\end{tabular}
\end{table}</code></pre>
</div>
</div>
<p><span class="math display">\[
\text{HighHost} =
\begin{cases}
1 &amp; \text{if } \text{host_listings_count} &gt; 2. \\
0 &amp; \text{otherwise}
\end{cases}
\]</span></p>
<p>We have chosen to use 2 to be the threshold value used to define the binary target variable. This is appropriate as 27.4% of our training data shows hosts with more than 2 listings, and this is an indication of whether the host owns a portfolio of properties or if they are just listing their primary or secondary property.</p>
</section>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2:</h2>
<section id="a" class="level3">
<h3 class="anchored" data-anchor-id="a">a)</h3>
<section id="data-pre-processing" class="level4">
<h4 class="anchored" data-anchor-id="data-pre-processing">Data Pre-Processing:</h4>
</section>
<section id="regularised-elastic-net-logistic-regression" class="level4">
<h4 class="anchored" data-anchor-id="regularised-elastic-net-logistic-regression">Regularised Elastic-Net Logistic Regression:</h4>
<p>REGULARISED ELASTIC-NET LOGISTIC REGRESSION INSPECTION:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="A1_Quarto_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
cv.glmnet.formula(formula = HighHost ~ ., data = trainData, alpha = best_alpha_EN, 
    nfolds = 10, family = "binomial", type.measure = "auc", trace.it = TRUE, 
    keep = TRUE)

Model fitting options:
    Sparse model matrix: FALSE
    Use model.frame: FALSE
    Number of crossvalidation folds: 10
    Alpha: 0.23
    Deviance-minimizing lambda: 0.0001935441  (+1 SE): 0.01397545</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>35 x 1 sparse Matrix of class "dgCMatrix"
                                        lambda.min
(Intercept)                           1.268148e+02
host_response_timea few days or more -2.137178e+00
host_response_timewithin a day       -5.076405e-01
host_response_timewithin a few hours -9.888749e-03
host_response_timewithin an hour      8.752877e-01
host_response_rate                   -1.887435e-02
host_acceptance_rate                 -2.754663e-03
host_is_superhostf                   -3.048062e-01
host_is_superhostt                    3.007458e-01
latitude                              2.556286e+00
longitude                            -2.065770e+00
room_typeEntire home/apt             -4.622147e-01
room_typePrivate room                 4.524645e-01
accommodates                         -6.389764e-03
bathrooms                             2.011488e-01
bedrooms                             -8.351735e-02
beds                                 -3.987329e-02
price                                 3.419632e-05
minimum_nights                       -1.128194e-01
maximum_nights                        5.913867e-04
minimum_nights_avg_ntm                1.169064e-01
maximum_nights_avg_ntm               -2.237346e-04
availability_30                       6.816502e-03
availability_60                      -1.547470e-02
availability_90                       1.339136e-02
availability_365                     -2.066907e-04
number_of_reviews                    -3.262287e-03
reviews_per_month                     4.220085e-02
review_scores_rating                 -1.030492e+00
instant_bookablef                    -2.863274e-01
instant_bookablet                     2.883048e-01
host_since_days                      -2.546715e-04
has_email_verification               -3.789383e-02
has_phone_verification                5.489259e+00
has_work_email_verification           5.227214e-01</code></pre>
</div>
<div class="cell-output-display">
<p><img src="A1_Quarto_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The Regularised Elastic-Net Regression Model was used as a binary classification model for predicting whether a listing is a high host or not. Logistic regression was appropriate here because the response variable is binary, and it models the probability that an observation belongs to a class using the log-odds function. With a large set of predictors, ordinary logistic regression may over-fit. This is addressed by regularization, through the elastic-net penalty.</p>
<p>The elastic-net penalty combines the L1 (lasso) and L2 (ridge) penalties. The lasso component performs variable selection, shrinking some coefficients exactly to zero, while the ridge component shrinks coefficients to zero without necessarily removing them. Elastic-net is thus a useful combination of lasso and ridge regression.</p>
<p>We used the training set to fit our model, where we tuned the model to the two hyper-parameters: α, which controls the balance between ridge and lasso penalization, and λ, which controls the level of the penalty.</p>
<p>To tune the model we searched over the range of <span class="math inline">\(α \in (0,1)\)</span>, with step sizes of 0.01. For each value, a 10-fold cross validated elastic-net regression model was fitted, and the corresponding best λ value was selected internally in the function. We then compared each model corresponding to each α value (which had been tuned to its best λ value), and we picked our α value, and its corresponding λ value based off the best performing AUROC value (the largest).</p>
<p>The optimal alpha value that we chose was α = 0.23, and the corresponding lambda value of λ = 0.0001935441, and we then refitted the final elastic-net model on the training set with this chosen α value and its corresponding optimal λ.</p>
<p>CONVERTING HighHost TO BE A FACTOR:</p>
</section>
<section id="random-forest" class="level4">
<h4 class="anchored" data-anchor-id="random-forest">Random Forest:</h4>
<p>RANDOM FOREST FITTING INSPECTION:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="A1_Quarto_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
 randomForest(formula = HighHost ~ ., data = trainData, ntree = best_model_rf$ntree,      mtry = best_model_rf$mtry, nodesize = best_model_rf$nodesize,      importance = TRUE, do.trace = 50) 
               Type of random forest: classification
                     Number of trees: 200
No. of variables tried at each split: 4

        OOB estimate of  error rate: 19.1%
Confusion matrix:
      No  Yes class.error
No  2907  759   0.2070376
Yes  769 3565   0.1774342</code></pre>
</div>
<div class="cell-output-display">
<p><img src="A1_Quarto_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We used a random forest classifier to predict the binary response variable, HighHost. Random Forests are a tree-based method that build a large number of classification trees on bootstrap samples of the training data and then combine their predictions. This approach is useful because it can capture non-linear relationships and interactions between predictors. It is also generally less prone to over fitting than a single decision tree.</p>
<p>At each split in the tree, only a random subset of predictors are considered. This introduces randomness and reduces correlation between trees, which improves the overall model. Since the outcome is binary, the response variable was treated as a factor so that the model was fitted as a classification forest.</p>
<p>The model was fitted using the training set only. The hyper-parameters used to tune were:</p>
<ul>
<li><p>mtry = the number of predictors randomly chosen at each split</p></li>
<li><p>ntree = the total number of trees grown in the forest</p></li>
<li><p>nodesize = the minimum final node size, which dictates how deep the trees grow</p></li>
</ul>
<p><span class="math inline">\(mtry \in \{2,4,6,8,10,12\}\)</span></p>
<p><span class="math inline">\(ntree \in \{100, 200, 300\}\)</span></p>
<p><span class="math inline">\(nodesize \in \{1,5,10\}\)</span></p>
<p>This gave a total of <span class="math inline">\(6 \times 3 \times 3 = 54\)</span> different models. The mtry values were chosen to cover values around the default value of approximately <span class="math inline">\(\sqrt{p}\)</span>, where <span class="math inline">\(p\)</span> is the number of predictors. The ntree values were chosen to compare a relatively small, moderate and large forest, and the nodesize values were chosen to allow a comparison between shallower, more moderate and deeper trees.</p>
<p>Hyper-parameter tuning was performed on 10-fold cross-validation on the training set. For each different combination of hyper-parameters, a new model was trained on 9 folds and the AUROC was calculated on the remaining fold. The mean AUROC across the 10-folds was then used to tune the model. The selected random forest hyper-parameters were then chosen to be: mtry = 12, ntree = 700 and nodesize = 1.</p>
<p>We can see that the optimal number of trees was on the upper boundary of our tuning Grid, but looking at our plots, we can see that the AUROC with respect to ntree is close to plateaued, so by extending our grid we would not gain much more accuracy. The same can be said for the mtry, as once mtry gets to 8, 10 and 12, the increases in AUROC were small.</p>
<p>The final random forest model was then refitted on the full training set using these selected hyper-parameters.</p>
</section>
<section id="gbm-boosted-tree-model" class="level4">
<h4 class="anchored" data-anchor-id="gbm-boosted-tree-model">GBM Boosted Tree Model:</h4>
<p>For the GBM boosted tree model, a gradient boosting classifier with a Bernoulli loss function was fitted to the training data, since the response variable HighHost is binary. The model builds many small decision trees sequentially, with each new tree focusing on correcting the errors made by the previous ensemble. This allows the method to capture non-linear effects and interactions among the predictors while still being tuned in a controlled way.</p>
<p>Hyperparameter selection was carried out using a grid-search approach on the training set only. For each candidate combination of tuning parameters, a GBM model was fitted with 10-fold cross-validation and model performance was assessed using the cross-validated Bernoulli deviance. The preferred hyperparameter combination was the one that achieved the lowest cross-validated error without risk of overfitting to the training data. After identifying the best combination of values for these hyperparameters the final GBM model has been refitted using these values.</p>
<p>The hyperparameter search space was:</p>
<p>n.trees ∈ {500, 750, 1000, 1250, 1500}</p>
<p>interaction.depth ∈ {3, 5, 8, 10}</p>
<p>shrinkage ∈ {0.01, 0.05, 0.1}</p>
<p>n.minobsinnode ∈ {5, 10, 20}</p>
<p>This gives a total of 6 × 5 × 5 × 3 = 450 hyperparameter combinations evaluated.</p>
<p>GBM BOOSTED TREE MODEL FITTING:</p>
<p>GBM BOOSTED TREE MODEL TUNING:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="A1_Quarto_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Although the highest AUROC values were achieved in the more complex regions of the grid, the gains beyond moderate settings were very small. A tuning choice of n.trees = 1000, interaction.depth = 5, shrinkage = 0.05, and n.minobsinnode = 10 was therefore selected as a balanced specification, providing strong predictive performance while avoiding unnecessary additional model complexity.</p>
</section>
<section id="k-nearest-neighbours-model" class="level4">
<h4 class="anchored" data-anchor-id="k-nearest-neighbours-model">K-Nearest Neighbours Model:</h4>
<p>For the K-nearest neighbours model, a supervised classification approach was used in which each observation is classified according to the majority class among its k nearest neighbours in the predictor space. Because KNN is distance-based, predictor scaling is important, so all predictors are centred and scaled before model fitting. Model selection was performed on the training set only using 10-fold cross-validation, with the optimal value of k chosen as the one that maximised the cross-validated ROC measure.</p>
<p>In addition to tuning the number of neighbours, the model has also been tuned over feature subsets. This is done because KNN can be highly sensitive to irrelevant or weak predictors and as a result including too many variables can distort the distance calculation and reduce classification performance. In order to explore and exploit this influence and subset size relationship a series of five different feature sets of increasing size have therefore been considered with each feature’s selection in it being dependent on its Relative Influence as depicted below;</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="A1_Quarto_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The feature search space consisted of the following candidate subsets:</p>
<p>Subset1: host_acceptance_rate, host_response_time, host_since_days</p>
<p>Subset2: host_acceptance_rate, host_response_time, host_since_days, host_response_rate</p>
<p>Subset3: host_acceptance_rate, host_response_time, host_since_days, host_response_rate, minimum_nights</p>
<p>Subset4: host_acceptance_rate, host_response_time, host_since_days, host_response_rate, minimum_nights, latitude</p>
<p>Subset5: host_acceptance_rate, host_response_time, host_since_days, host_response_rate, minimum_nights, latitude, price</p>
<p>The neighbourhood size search space was:</p>
<p>k ∈ {3,5,7,…,25}</p>
<p>So the KNN tuning process searched jointly across 5 candidate feature sets and 12 candidate values of k.</p>
<p>K-NEAREST NEIGHBOURS INSPECTION:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="A1_Quarto_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The KNN model was tuned over alternative feature subsets and values of k. Based on the highest mean cross-validated AUROC. The preferred specification uses the feature set Subset2 which includes host_acceptance_rate, host_response_time, host_since_days and host_response_rate as features. Although performance for this feature set declines gradually as k increases, it remains the strongest overall, indicating that these 4 host-related variables carry the most predictive signal for this classifier.</p>
<p>Despite the highest mean cross-validated ROC being achieved by the Host feature set at k=1, a slightly larger value such as k=3 should be preferred in practice. This is because k=1 can be highly sensitive to noise and individual observations in the training data, whereas k=3 still delivers very strong predictive performance while providing a more stable and robust classification rule. The final choice therefore balances peak cross-validated accuracy against model stability and reduced sensitivity to local irregularities. The KNN tuning results show that predictive performance is strongest at very small values of k, with AUROC declining as the number of neighbours increases. This suggests that the class structure is highly local and that larger neighbourhood sizes introduce excessive smoothing. The best-performing feature sets were the smaller host-related subsets, while adding further predictors reduced performance, indicating that KNN was sensitive to irrelevant or weakly informative variables. Although the highest AUROC was achieved at k=1, a slightly larger value such as k=3 may be preferred as a more stable specification with very similar performance.</p>
</section>
</section>
<section id="b" class="level3">
<h3 class="anchored" data-anchor-id="b">b)</h3>
<section id="model-performance-metric-summary" class="level4">
<h4 class="anchored" data-anchor-id="model-performance-metric-summary">5 Model Performance Metric Summary:</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>CV perfomance metrics</caption>
<colgroup>
<col style="width: 22%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: center;">Accuracy</th>
<th style="text-align: center;">F1 score</th>
<th style="text-align: center;">Precision</th>
<th style="text-align: center;">Recall</th>
<th style="text-align: center;">Specificity</th>
<th style="text-align: center;">AUROC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Elastic Net</td>
<td style="text-align: center;">0.664</td>
<td style="text-align: center;">0.640</td>
<td style="text-align: center;">0.762</td>
<td style="text-align: center;">0.551</td>
<td style="text-align: center;">0.797</td>
<td style="text-align: center;">0.748</td>
</tr>
<tr class="even">
<td style="text-align: left;">Random Forest</td>
<td style="text-align: center;">0.822</td>
<td style="text-align: center;">0.837</td>
<td style="text-align: center;">0.833</td>
<td style="text-align: center;">0.840</td>
<td style="text-align: center;">0.801</td>
<td style="text-align: center;">0.902</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GBM Boosted Tree</td>
<td style="text-align: center;">0.810</td>
<td style="text-align: center;">0.825</td>
<td style="text-align: center;">0.823</td>
<td style="text-align: center;">0.827</td>
<td style="text-align: center;">0.789</td>
<td style="text-align: center;">0.887</td>
</tr>
<tr class="even">
<td style="text-align: left;">KNN</td>
<td style="text-align: center;">0.753</td>
<td style="text-align: center;">0.790</td>
<td style="text-align: center;">0.733</td>
<td style="text-align: center;">0.856</td>
<td style="text-align: center;">0.632</td>
<td style="text-align: center;">0.840</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<p><img src="A1_Quarto_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">Question 3:</h2>
<p>###a)</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    tau Accuracy  F1.Score Precision    Recall Specificity
45 0.45   0.8085 0.8327146 0.7904229 0.8797877   0.7242226</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="A1_Quarto_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>###b)</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="A1_Quarto_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="c" class="level3">
<h3 class="anchored" data-anchor-id="c">c)</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Accuracy F1.Score Precision Recall Specificity  AUROC
1   0.8085   0.8327    0.7904 0.8798      0.7242 0.8967</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Accuracy F1.Score Precision Recall Specificity  AUROC
1   0.8075   0.8306     0.788 0.8781      0.7254 0.8983</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                  Set Accuracy  F1.Score Precision    Recall Specificity
1   CV at optimal tau   0.8085 0.8327146 0.7904229 0.8797877   0.7242226
2 Test at optimal tau   0.8075 0.8306203 0.7879800 0.8781395   0.7254054
      AUROC
1 0.8967169
2 0.8983366</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Best Tau: 0.45</code></pre>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>